# Generated by Django 4.2.6 on 2023-11-30 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('idUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=12)),
                ('puntos', models.PositiveIntegerField(default=0)),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=50)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('pais', models.CharField(max_length=50, null=True)),
                ('idUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=80)),
                ('telefono', models.BigIntegerField()),
                ('descripcion', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Orden_de_compra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token_ws', models.CharField(default=0, max_length=255)),
                ('tarjeta', models.CharField(default=0, max_length=10)),
                ('fecha_transbank', models.CharField(default='0', max_length=100)),
                ('estado_transbank', models.CharField(default='0', max_length=100)),
                ('monto', models.PositiveIntegerField()),
                ('users_metadata', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=150)),
                ('precio', models.PositiveIntegerField()),
                ('stock', models.SmallIntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, upload_to='imagenes/')),
                ('activo', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.BigIntegerField()),
                ('fecha', models.DateField(auto_now=True, null=True)),
                ('hora', models.DateTimeField(auto_now=True, null=True)),
                ('trimestre', models.PositiveSmallIntegerField()),
                ('idCliente', models.ManyToManyField(db_table='compras_x_usuarios', to='aplicacion.clientes')),
                ('idProducto', models.ManyToManyField(db_table='detalle_venta_producto', to='aplicacion.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='idTipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplicacion.tipoproducto', verbose_name='categoria'),
        ),
        migrations.CreateModel(
            name='Orden_de_compra_detalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('id_orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.orden_de_compra')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplicacion.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('fecha', models.DateField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.producto')),
                ('users_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_total', models.BigIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aplicacion.producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
